### ISSUE TITLE
The tool does not auto convert gtx textures when loading environment.

### ISSUE THREAD

**Issue by CppHustler** [MrMatynator/MatyKalMapEditor#1]
Hi, thanks for great work, 
I've downloaded the latest update related to the texture, but I found that the program gets closes after loading the KCM immediately.

Best wishes

**Comment by spicman** [comment]
Are you sure about that?  If I choose load entire world or load a KCM, it works just fine.

Haven't had a close at all and been trying to reproduce your issue.  Tell me which KCM you loaded.

**Comment by spicman** [comment]
I loaded up 32_29 (temp) and emok, cop ... they are all loading just fine.  

![image](https://user-images.githubusercontent.com/72982890/191112467-32235d71-7064-43bc-a0e0-56f748ee8cc8.png)

What about your ini settings I assume they are correct?

**Comment by MrMatynator** [comment]
The issue he has was related to dds convert on env load :D nothing with kcm specifically.
