### ISSUE TITLE
Object related issues

### ISSUE THREAD

**Issue by ales676** [MrMatynator/MatyKalMapEditor#12]
1. If you don't add a new object, the "OPL Saving" Window will not show up therefore can't save.
2. if an object has no path (data/object/etc), add a node to present it in the editor so that user can select and delete it, or edit it.
3. asking user to load OPL along with KCM would be useful too,
	lets say i loaded 31_31.KCM,
	if it asks me "Would you like to load 31_31.OPL too?" Would be useful
4. when "Object Edit Tools" Mini window is opened, show there the object's X Y Z and Path too (data/object/2021/etc) when an object is selected

**Comment by MrMatynator** [comment]
- [ ] 1: Register all types of edits 
- [ ] 2: Fix object pathing
- [ ] 3: Not really that great because of multiselect in opening.
- [ ] 4: Will be taken into count when doing bigger opl update pass.
