### ISSUE TITLE
Map Editor closing

### ISSUE THREAD

**Issue by spicman** [MrMatynator/MatyKalMapEditor#4]
The issue is apparent when you have Autoload World enabled.

I have tried it with Korean Test client, and it opens just fine (loads entire world).  If I try to use Map Editor with my client, it closes soon after the map loading process.

If I have the feature off, then I can load my client and individual maps.  This leads me to believe possible a KCM/OPL issue?

Here is a short clip: https://www.youtube.com/watch?v=r3EXvjakgUM

**Comment by MrMatynator** [comment]
Look at your clip.. pauze it on 25 seconds. you will see it errored on a environment texture.. the last one.. index 96. See if that texture is present in dds form. also empty string in your env at index 97 wich is a inix derpo :D.

**Comment by spicman** [comment]
This is a non-issue.  I found out the slow way (replacing map by map) and forgot I had placed some test maps in here to check out.  Those were causing the program to crash.  These maps are custom maps not INIX maps.  Thanks!
